version: "3.8"

services:
  db:
    image: postgres
    container_name: triptimize_db
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
