spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: false
  main:
    web-application-type: servlet
  quartz:
    job-store-type: memory

logging:
  level:
    org:
      springframework:
        web: error
        security: error
        data: error
        jpa: error
      hibernate:
        type: error
      quartz: error
