spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  main:
    web-application-type: servlet

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        data: DEBUG
        jpa: DEBUG
        hibernate: DEBUG
        sql: DEBUG
